.TH STEMWORDS "1" "March 2010" "Snowball" "User Commands"
.SH NAME
stemwords \- Snowball word stemming utility
.SH DESCRIPTION
.B stemwords
.RB [ \-l
.IR language ]
.RB [ \-i
.IR "input file" ]
.RB [ \-o
.IR "output file" ]
.RB [ \-c
.IR "character encoding" ]
.RB [ \-p [ 2 "]] [" \-h ]
.PP
The input file consists of a list of words to be stemmed, one per line.
Words should be in lower case, but (for English) A\-Z letters are mapped
to their a\-z equivalents anyway.
If omitted, stdin is used.
.PP
If \fB\-c\fR is given, the argument is the character encoding of the
input and output files.
If it is omitted, the UTF\-8 encoding is used.
.PP
If \fB\-p\fR is given the output file consists of each word of the input
file followed by "\->" followed by its stemmed equivalent.
If \fB\-p2\fR is given the output file is a two column layout containing
the input words in the first column and the stemmed equivalents in the
second column.
Otherwise, the output file consists of the stemmed words, one per line.
